apiVersion: v1
kind: Service
metadata:
  name: {{ include "geohubapp.fullname" . }}
  labels:
    {{- include "geohubapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: http

      {{- if .Values.service.targetPort }}
      # ahuarte: 'TargetPort' property is included.
      targetPort: {{ .Values.service.targetPort }}
      {{- else }}
      targetPort: http
      {{- end }}
            
      {{- if .Values.service.nodePort }}
      # ahuarte: 'NodePort' property is included.
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}

  selector:
    {{- include "geohubapp.selectorLabels" . | nindent 4 }}
